CREATE TABLE IF NOT EXISTS public."MSB_APP_NOTIFICATION" (
    "NOTIFICATION_ID" VARCHAR(20) PRIMARY KEY,
    "NOTIFICATION_TYPE" VARCHAR(50),
    "NOTIFICATION_HEADER" VARCHAR(50),
    "MSG_EN" TEXT,
    "MSG_MSB" TEXT,
    "START_DATE" DATE,
    "END_DATE" DATE,
    "NOTIFICATION_IMG1" character varying(500),
    "URL1_IDENTIFIER_VID_EN" character varying(500),
    "URL2_IDENTIFIER_VID_MSB" character varying(500),
    "URL3_IDENTIFIER_DOC_EN" character varying(500),
    "URL4_IDENTIFIER_DOC_MSB" character varying(500),
    "FILLER1" character varying(50),
    "FILLER2" character varying(50),
    "FILLER3" character varying(50),
    "PROMOTION_ID" character varying(50),
    "PROMOTION_TITLE" character varying(50),
    "DELETE_FLAG" VARCHAR(20),
    "CREATED_BY" character varying(20),
    "CREATED_ON" timestamp(6) without time zone,
    "MODIFIED_BY" character varying(20),
    "MODIFIED_ON" timestamp(6) without time zone,
    "STATUS" VARCHAR(50)
);
