CREATE TABLE IF NOT EXISTS public."MSB_SMS" (
    "COUNTRY" VARCHAR(20),
    "SOURCE" VARCHAR(1000),
    "MESSAGE" VARCHAR(500),
    "CONTACT_NO" VARCHAR(20),
    "CREATED_ON" timestamp(6) without time zone,
    "DELIVRED_STATUS" VARCHAR(50),
    "MESSAGE_ID" VARCHAR(50),
    "RESPONSE_JSON" TEXT,
    "DELIVERY_MESSAGE" TEXT
);