CREATE TABLE IF NOT EXISTS public."MSB_INBOUND_SMS" (
    "SENT_ON" VARCHAR(100),
    "BP" VARCHAR(20),
    "MOBILE_NUMBER" VARCHAR(20),
    "SCRATCHCODE" VARCHAR(50),
    "TXN_TYPE" VARCHAR(50),
    "LANGUAGE" VARCHAR(4),
    "REASON" VARCHAR(50),
    "SMS_SENT" TEXT,
    "CREATED_DATE" timestamp(6) without time zone
);