CREATE TABLE IF NOT EXISTS public."MSB_NOTILOG_CONTRA" (
    "CONTRACTOR" VARCHAR(20),
    "NOTIFICATION_ID" VARCHAR(20),
    "NOTIFICATION_READ_FLAG" VARCHAR(20),
    "NOTI_TYPE" VARCHAR(50),
    "TITLE" VARCHAR(50),
    "MSG_EN" TEXT,
    "MAG_MSB" TEXT,
    "URL1_READ_FLAG" VARCHAR(20),
    "URL2_READ_FLAG" VARCHAR(20),
    "URL3_READ_FLAG" VARCHAR(20),
    "URL4_READ_FLAG" VARCHAR(20),
    "START_DATE" DATE,
    "END_DATE" DATE,
    "CREATED_BY" VARCHAR(20),
    "CREATED_ON" timestamp(6) without time zone,
    "MODIFIED_BY" VARCHAR(20),
    "MODIFIED_ON" timestamp(6) without time zone
);