CREATE TABLE IF NOT EXISTS public."MSG_HOMEPAGE_CONTROL" (
    "BP_NUMBER" VARCHAR(20) ,
    "PRODUCT_INFORMATION" VARCHAR(3) ,
    "PRODUCT_LIFTING" VARCHAR(3) ,
    "POINTS" VARCHAR(3) ,
    "TRANSACTION_HISTORY" VARCHAR(3) ,
    "MILESTONE" VARCHAR(3) ,
    "REDEMPTIONHISTORY" VARCHAR(20) 
);
