CREATE TABLE IF NOT EXISTS public."MSG_CONTRACTOR_DEALER_MAPPING" (
    "CONTRACTOR_BP" VARCHAR(20) ,
    "DEALER_BP" VARCHAR(20),
    "MOB_NO" VARCHAR(20),
    "NAME" VARCHAR(20),
    "REGION" VARCHAR(200)
);
